[package]
name = "client-native-rift"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21", features = ["full"] }
tokio-tungstenite = "*"

serde = { version = "1.0.144", features = ["derive"] }
serde_json = "*"

env_logger = "0.8"
log = "0.4"

fastpbkdf2 = "0.1.0"
aes-gcm = "0.10.1"
base64 = "0.13.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
