[package]
name = "client-native-rift"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21", features = ["full"] }
futures-util = "0.3.24"

webrtc = "0.5.0"
tokio-tungstenite = { version = "*", features = ["rustls-tls"] }
url = "2.3.1"

serde = { version = "1.0.144", features = ["derive"] }
serde_json = "*"

clap = { version = "3.2.21", features = ["derive"] }
env_logger = "0.8"
log = "0.4"

fastpbkdf2 = "0.1.0"
aes-gcm = "0.10.1"
sha256 = "1.0.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
base64 = "0.13.0"
