[package]
name = "keks-meet"
version = "0.1.0"
edition = "2021"

[dependencies]
client-native-lib = { path = "../client-native-lib" }

clap = { version = "4.1.1", features = ["derive"] }
async-std = "1.12.0"
tokio = { version = "1.24.1", features = ["full"] }
env_logger = "0.10.0"
log = "0.4"
anyhow = "1.0.68"
crossbeam-channel = "0.5.6"

egui = "0.20.1"
eframe = "0.20.1"

libmpv = { git = "https://github.com/sirno/libmpv-rs.git", branch = "upgrade-libmpv" }

