[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1.21", features = ["full"] }
log = "0.4"
env_logger = "0.8"
futures-util = "0.3.24"
listenfd = "1.0.0"
hyper = "0.14.20"
